### ISSUE TITLE
add params for app

### ISSUE THREAD

**Issue by Oleh-Hrebchuk** [SoftServeInc/django-easy-login#7]
class_name - class name for "User" object. Defaults to User model.
collection_method - method which returns collection of users. Sample: .all, .active, .admins, .groupped_users. Value is a simple. Defaults to :all.
name_method - default value is proc { |e| [e.email, e.id] }. You can change the label of users displayed in dropdown. For example you can add roles, permissions and any other important information.
limit - limit number of records in dropdown. Default 10. You can put :none if you don't want to limit the number of users for select.
redirect_path_after_login - redirect user to path. Default is :root_path.
login_on - you can enable login with select field, ID input or both. Default: :both.
login_button_label - login button label.
auto_show - automatically show AnyLogin box.

**Comment by matiyashpr** [comment]
Completed all requirements.
